### ISSUE TITLE
Document how to use spotbugs-jspecify-plugin

### ISSUE THREAD

**Issue by alexandrenavarro** [spotbugs/spotbugs-jspecify-plugin#139]
Hi,

I don't understand how to use spotbugs-jspecify-plugin instead of standard spotbugs-maven-plugin or spotbugs-gradle-
plugin.
Now I use jspecify instead of dormant jsr-305 and it should be very useful to use it in spotbugs.
Can you document it how to do it, please?
I'm not sure why it is not integrate in spotbugs-maven-plugin or spotbugs-gradle-
plugin and there is a need to have another plugin.

**Comment by KengoTODA** [comment]
This project is inactive, see https://github.com/jspecify/jspecify/pull/399
